### PR TITLE
adds options to enable alignment of spinner to either side of the button text

### PR DESCRIPTION
**Pull request by feiwaltan**
left and right are the only options that should be valid, but I did not check the values, didn't see any other place in the code where the string values were being validates.

### CODE REVIEW

**Comment by yury-dymov** [comment]
Looks good to me. Let Travis validate the build and if all tests are passed, I am merging and issuing a new version soon.

**Comment by feiwaltan** [comment]
cool, did you want to add test coverage as well as update the documentation/usage info?

**Comment by yury-dymov** [comment]
I will update the documentation and I don't care much about test coverage :)

**Comment by zimmelbc** [comment]
I'm having trouble getting the spinAlignment to work. It always remains left-aligned and I cannot get it right-aligned. I am able to set the spinColor prop fine. Any advise?

`<Button className="btn btn-primary" disabled={!this.state.emailAddressValid} onClick={this.signInClick} loading={this.state.loading} spinAlignment="right">Sign In</Button>`

**Comment by feiwaltan** [comment]
@zimmelbc 
Have you attempted using the `btStyle` option instead of the `className` to get the styling to be correct?
Its possible there's an override in your css somewhere on the `btn btn-primary` class that's changing the alignment.

Without seeing more about the context here it'll be difficult to troubleshoot further, hope that helps.

**Comment by zimmelbc** [comment]
@feiwaltan I initially removed className thinking the same that it might be overriding the styling on the spinner. I just tried using btStyle but the spinner is still aligned on the left. WHen inspecting the spinner element, I never see "float" being applied to the div set to display: inline-block.

**Pull request merged**
